name: Unit and Integration Tests
on:
  workflow_call:
    inputs:
      filters:
        required: false
        type: string

permission: read-all

jobs:
  name: Tests
  runs-on: ${{ matrix.os }}
  strategy:
    fail-fast: false
    matrix:
      os: [ubuntu-latest, macos-latest]
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: npm ci

    - name: Run unit and integration tests
      run: npm test --ci ${{ inputs.filters }}